// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: metricsv1/metrics.proto

// Phase 1 live-streaming contract: a server-streaming RPC mirroring the SSE
// /api/v1/stream/metrics feed. gRPC clients get the same MetricsUpdate payloads.

package metricsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RealtimeBucket struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BucketStart    string                 `protobuf:"bytes,1,opt,name=bucket_start,json=bucketStart,proto3" json:"bucket_start,omitempty"` // RFC3339 UTC
	Revenue        float64                `protobuf:"fixed64,2,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Orders         int64                  `protobuf:"varint,3,opt,name=orders,proto3" json:"orders,omitempty"`
	ActiveSessions int64                  `protobuf:"varint,4,opt,name=active_sessions,json=activeSessions,proto3" json:"active_sessions,omitempty"`
	UpdatedAt      string                 `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // RFC3339 UTC
	AnomalyFlag    bool                   `protobuf:"varint,6,opt,name=anomaly_flag,json=anomalyFlag,proto3" json:"anomaly_flag,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RealtimeBucket) Reset() {
	*x = RealtimeBucket{}
	mi := &file_metricsv1_metrics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeBucket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeBucket) ProtoMessage() {}

func (x *RealtimeBucket) ProtoReflect() protoreflect.Message {
	mi := &file_metricsv1_metrics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeBucket.ProtoReflect.Descriptor instead.
func (*RealtimeBucket) Descriptor() ([]byte, []int) {
	return file_metricsv1_metrics_proto_rawDescGZIP(), []int{0}
}

func (x *RealtimeBucket) GetBucketStart() string {
	if x != nil {
		return x.BucketStart
	}
	return ""
}

func (x *RealtimeBucket) GetRevenue() float64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *RealtimeBucket) GetOrders() int64 {
	if x != nil {
		return x.Orders
	}
	return 0
}

func (x *RealtimeBucket) GetActiveSessions() int64 {
	if x != nil {
		return x.ActiveSessions
	}
	return 0
}

func (x *RealtimeBucket) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *RealtimeBucket) GetAnomalyFlag() bool {
	if x != nil {
		return x.AnomalyFlag
	}
	return false
}

type Anomaly struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	BucketStart   string                 `protobuf:"bytes,3,opt,name=bucket_start,json=bucketStart,proto3" json:"bucket_start,omitempty"` // RFC3339 UTC
	Observed      float64                `protobuf:"fixed64,4,opt,name=observed,proto3" json:"observed,omitempty"`
	Expected      float64                `protobuf:"fixed64,5,opt,name=expected,proto3" json:"expected,omitempty"`
	ZScore        float64                `protobuf:"fixed64,6,opt,name=z_score,json=zScore,proto3" json:"z_score,omitempty"`
	Severity      string                 `protobuf:"bytes,7,opt,name=severity,proto3" json:"severity,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	DetectedAt    string                 `protobuf:"bytes,9,opt,name=detected_at,json=detectedAt,proto3" json:"detected_at,omitempty"` // RFC3339 UTC
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Anomaly) Reset() {
	*x = Anomaly{}
	mi := &file_metricsv1_metrics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Anomaly) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Anomaly) ProtoMessage() {}

func (x *Anomaly) ProtoReflect() protoreflect.Message {
	mi := &file_metricsv1_metrics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Anomaly.ProtoReflect.Descriptor instead.
func (*Anomaly) Descriptor() ([]byte, []int) {
	return file_metricsv1_metrics_proto_rawDescGZIP(), []int{1}
}

func (x *Anomaly) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Anomaly) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *Anomaly) GetBucketStart() string {
	if x != nil {
		return x.BucketStart
	}
	return ""
}

func (x *Anomaly) GetObserved() float64 {
	if x != nil {
		return x.Observed
	}
	return 0
}

func (x *Anomaly) GetExpected() float64 {
	if x != nil {
		return x.Expected
	}
	return 0
}

func (x *Anomaly) GetZScore() float64 {
	if x != nil {
		return x.ZScore
	}
	return 0
}

func (x *Anomaly) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Anomaly) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Anomaly) GetDetectedAt() string {
	if x != nil {
		return x.DetectedAt
	}
	return ""
}

type MetricsUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Snapshot        []*RealtimeBucket      `protobuf:"bytes,1,rep,name=snapshot,proto3" json:"snapshot,omitempty"`                                        // sent once right after connect
	Current         *RealtimeBucket        `protobuf:"bytes,2,opt,name=current,proto3" json:"current,omitempty"`                                          // latest 1-minute bucket
	Anomaly         *Anomaly               `protobuf:"bytes,3,opt,name=anomaly,proto3" json:"anomaly,omitempty"`                                          // set when a new anomaly fired
	SpeedMultiplier float64                `protobuf:"fixed64,4,opt,name=speed_multiplier,json=speedMultiplier,proto3" json:"speed_multiplier,omitempty"` // replay pacing
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`                                            // "live" | "replay"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MetricsUpdate) Reset() {
	*x = MetricsUpdate{}
	mi := &file_metricsv1_metrics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsUpdate) ProtoMessage() {}

func (x *MetricsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_metricsv1_metrics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsUpdate.ProtoReflect.Descriptor instead.
func (*MetricsUpdate) Descriptor() ([]byte, []int) {
	return file_metricsv1_metrics_proto_rawDescGZIP(), []int{2}
}

func (x *MetricsUpdate) GetSnapshot() []*RealtimeBucket {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *MetricsUpdate) GetCurrent() *RealtimeBucket {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *MetricsUpdate) GetAnomaly() *Anomaly {
	if x != nil {
		return x.Anomaly
	}
	return nil
}

func (x *MetricsUpdate) GetSpeedMultiplier() float64 {
	if x != nil {
		return x.SpeedMultiplier
	}
	return 0
}

func (x *MetricsUpdate) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StreamMetricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamMetricsRequest) Reset() {
	*x = StreamMetricsRequest{}
	mi := &file_metricsv1_metrics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamMetricsRequest) ProtoMessage() {}

func (x *StreamMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metricsv1_metrics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamMetricsRequest.ProtoReflect.Descriptor instead.
func (*StreamMetricsRequest) Descriptor() ([]byte, []int) {
	return file_metricsv1_metrics_proto_rawDescGZIP(), []int{3}
}

var File_metricsv1_metrics_proto protoreflect.FileDescriptor

const file_metricsv1_metrics_proto_rawDesc = "" +
	"\n" +
	"\x17metricsv1/metrics.proto\x12\rabi.metricsv1\"\xd0\x01\n" +
	"\x0eRealtimeBucket\x12!\n" +
	"\fbucket_start\x18\x01 \x01(\tR\vbucketStart\x12\x18\n" +
	"\arevenue\x18\x02 \x01(\x01R\arevenue\x12\x16\n" +
	"\x06orders\x18\x03 \x01(\x03R\x06orders\x12'\n" +
	"\x0factive_sessions\x18\x04 \x01(\x03R\x0eactiveSessions\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\tupdatedAt\x12!\n" +
	"\fanomaly_flag\x18\x06 \x01(\bR\vanomalyFlag\"\xfa\x01\n" +
	"\aAnomaly\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12!\n" +
	"\fbucket_start\x18\x03 \x01(\tR\vbucketStart\x12\x1a\n" +
	"\bobserved\x18\x04 \x01(\x01R\bobserved\x12\x1a\n" +
	"\bexpected\x18\x05 \x01(\x01R\bexpected\x12\x17\n" +
	"\az_score\x18\x06 \x01(\x01R\x06zScore\x12\x1a\n" +
	"\bseverity\x18\a \x01(\tR\bseverity\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1f\n" +
	"\vdetected_at\x18\t \x01(\tR\n" +
	"detectedAt\"\xf8\x01\n" +
	"\rMetricsUpdate\x129\n" +
	"\bsnapshot\x18\x01 \x03(\v2\x1d.abi.metricsv1.RealtimeBucketR\bsnapshot\x127\n" +
	"\acurrent\x18\x02 \x01(\v2\x1d.abi.metricsv1.RealtimeBucketR\acurrent\x120\n" +
	"\aanomaly\x18\x03 \x01(\v2\x16.abi.metricsv1.AnomalyR\aanomaly\x12)\n" +
	"\x10speed_multiplier\x18\x04 \x01(\x01R\x0fspeedMultiplier\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x16\n" +
	"\x14StreamMetricsRequest2f\n" +
	"\x0eMetricsService\x12T\n" +
	"\rStreamMetrics\x12#.abi.metricsv1.StreamMetricsRequest\x1a\x1c.abi.metricsv1.MetricsUpdate0\x01B Z\x1eabi/internal/grpcapi/metricsv1b\x06proto3"

var (
	file_metricsv1_metrics_proto_rawDescOnce sync.Once
	file_metricsv1_metrics_proto_rawDescData []byte
)

func file_metricsv1_metrics_proto_rawDescGZIP() []byte {
	file_metricsv1_metrics_proto_rawDescOnce.Do(func() {
		file_metricsv1_metrics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metricsv1_metrics_proto_rawDesc), len(file_metricsv1_metrics_proto_rawDesc)))
	})
	return file_metricsv1_metrics_proto_rawDescData
}

var file_metricsv1_metrics_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_metricsv1_metrics_proto_goTypes = []any{
	(*RealtimeBucket)(nil),       // 0: abi.metricsv1.RealtimeBucket
	(*Anomaly)(nil),              // 1: abi.metricsv1.Anomaly
	(*MetricsUpdate)(nil),        // 2: abi.metricsv1.MetricsUpdate
	(*StreamMetricsRequest)(nil), // 3: abi.metricsv1.StreamMetricsRequest
}
var file_metricsv1_metrics_proto_depIdxs = []int32{
	0, // 0: abi.metricsv1.MetricsUpdate.snapshot:type_name -> abi.metricsv1.RealtimeBucket
	0, // 1: abi.metricsv1.MetricsUpdate.current:type_name -> abi.metricsv1.RealtimeBucket
	1, // 2: abi.metricsv1.MetricsUpdate.anomaly:type_name -> abi.metricsv1.Anomaly
	3, // 3: abi.metricsv1.MetricsService.StreamMetrics:input_type -> abi.metricsv1.StreamMetricsRequest
	2, // 4: abi.metricsv1.MetricsService.StreamMetrics:output_type -> abi.metricsv1.MetricsUpdate
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_metricsv1_metrics_proto_init() }
func file_metricsv1_metrics_proto_init() {
	if File_metricsv1_metrics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metricsv1_metrics_proto_rawDesc), len(file_metricsv1_metrics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metricsv1_metrics_proto_goTypes,
		DependencyIndexes: file_metricsv1_metrics_proto_depIdxs,
		MessageInfos:      file_metricsv1_metrics_proto_msgTypes,
	}.Build()
	File_metricsv1_metrics_proto = out.File
	file_metricsv1_metrics_proto_goTypes = nil
	file_metricsv1_metrics_proto_depIdxs = nil
}
